name: Publish SETi Nuget Package
on:
  push:
    branches:
      - dev
    tags:
      - v*
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .Net SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          source-url: https://nuget.pkg.github.com/Sensor-Electronic-Technology/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      - name: Make Nuget Packages
        run: dotnet pack MongoDB.Entities/MongoDB.Entities.csproj -c Release
      - name: Publish To Nuget
        run: dotnet nuget push MongoDB.Entities/bin/Release/*.nupkg --skip-duplicate
