name: Publish SETi Nuget Package
on:
  push:
    tags:
      - v*
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .Net SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          source-url: https://nuget.pkg.github.com/Sensor-Electronic-Technology/index.json
      - name: Make Nuget Packages
        run: dotnet pack MongoDB.Entities/MongoDB.Entities.csproj -c Release
      - name: Publish To Nuget
        run: dotnet nuget push MongoDB.Entities/bin/Release/*.nupkg --skip-duplicate
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: changelog.md
        # uses: softprops/action-gh-release@v1
        # if: ${{ !contains(github.ref, 'beta') }}
        # with:
        #   draft: false
        #   name: ${{ github.ref_name }} Release
        #   body_path: changelog.md
